FROM node:carbon

LABEL MAINTAINER="Harith Javed <harith.bakhrani@andela.com>"
LABEL application="travella-backend"

ENV TERM=xterm-256color

WORKDIR /usr/app

COPY dist /usr/app
COPY .sequelizerc /usr/app
